# Generated by Django 5.2.9 on 2025-12-17 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaudit',
            options={'ordering': ['-created_at'], 'verbose_name': "Journal d'audit", 'verbose_name_plural': "Journaux d'audit"},
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='categorie',
            field=models.CharField(choices=[('authentication', 'Authentification'), ('authorization', 'Autorisation'), ('data_create', 'Création'), ('data_read', 'Lecture'), ('data_update', 'Mise à jour'), ('data_delete', 'Suppression'), ('business_logic', 'Logique métier'), ('file_upload', 'Upload'), ('file_download', 'Téléchargement'), ('payment', 'Paiement'), ('contract', 'Contrat'), ('reservation', 'Réservation'), ('financing', 'Financement'), ('document', 'Document'), ('user_management', 'Gestion utilisateur'), ('system', 'Système')], default='system', help_text="Catégorie de l'action pour faciliter le filtrage", max_length=50),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='methode_http',
            field=models.CharField(blank=True, help_text='Méthode HTTP (GET, POST, PUT, DELETE, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='resultat',
            field=models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec'), ('partial', 'Partiel'), ('pending', 'En attente')], default='success', help_text="Résultat de l'action", max_length=20),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='session_key',
            field=models.CharField(blank=True, help_text='Clé de session Django pour tracer les sessions', max_length=40),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='url_path',
            field=models.CharField(blank=True, help_text='Chemin URL de la requête', max_length=500),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='acteur',
            field=models.ForeignKey(blank=True, help_text="Utilisateur ayant effectué l'action (peut être null pour les actions système)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='action',
            field=models.CharField(help_text='Action effectuée (ex: login, create, update, delete, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='objet_id',
            field=models.UUIDField(blank=True, help_text="ID de l'objet concerné (peut être null pour les actions globales)", null=True),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='objet_type',
            field=models.CharField(help_text="Type d'objet concerné (ex: Reservation, Paiement, etc.)", max_length=50),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (changements, erreurs, etc.)'),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User-Agent du navigateur', max_length=255),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['-created_at'], name='core_journa_created_3c70a7_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['acteur', '-created_at'], name='core_journa_acteur__977c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['categorie', '-created_at'], name='core_journa_categor_9ed3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['action', '-created_at'], name='core_journa_action_542f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalaudit',
            index=models.Index(fields=['resultat', '-created_at'], name='core_journa_resulta_8977ea_idx'),
        ),
    ]
