# Generated by Django 5.2.9 on 2025-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_journalaudit_options_journalaudit_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaudit',
            name='methode_http',
            field=models.CharField(blank=True, default='', help_text='Méthode HTTP (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Clé de session Django pour tracer les sessions', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='url_path',
            field=models.CharField(blank=True, default='', help_text='Chemin URL de la requête', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text='User-Agent du navigateur', max_length=255, null=True),
        ),
    ]
