# Generated by Django 5.2.9 on 2025-12-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
