# Generated by Django 5.2.9 on 2025-12-18 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, help_text='Token de réinitialisation (32 bytes hex)', max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Token déjà utilisé')),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du token (1h après création)")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP de l'utilisateur qui a demandé le reset", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de réinitialisation',
                'verbose_name_plural': 'Tokens de réinitialisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
