# Generated by Django 5.2.8 on 2025-11-10 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notaire', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='programmes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvancementChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_pointage', models.DateField()),
                ('pourcentage', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements', to='catalog.etapechantier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='chantiers/')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pris_le', models.DateTimeField()),
                ('avancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.avancementchantier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='etapechantier',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_chantier', to='catalog.programme'),
        ),
        migrations.CreateModel(
            name='ModeleBien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_marketing', models.CharField(max_length=255)),
                ('surface_hab_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_base_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='modeles/')),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='catalog.typebien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_lot', models.CharField(max_length=100)),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut_disponibilite', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu'), ('livre', 'Livré')], default='disponible', max_length=20)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('caracteristiques', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='unites/')),
                ('modele_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='catalog.modelebien')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='catalog.programme')),
            ],
            options={
                'unique_together': {('programme', 'reference_lot')},
            },
        ),
    ]
