# Generated by Django 5.2.8 on 2025-11-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avancementchantier',
            options={'ordering': ('etape', '-date_pointage'), 'verbose_name': 'Avancement de chantier', 'verbose_name_plural': 'Avancements de chantier'},
        ),
        migrations.AlterModelOptions(
            name='etapechantier',
            options={'ordering': ('programme', 'ordre'), 'verbose_name': 'Étape de chantier', 'verbose_name_plural': 'Étapes de chantier'},
        ),
        migrations.AlterModelOptions(
            name='modelebien',
            options={'ordering': ('nom_marketing',), 'verbose_name': 'Modèle de bien', 'verbose_name_plural': 'Modèles de biens'},
        ),
        migrations.AlterModelOptions(
            name='photochantier',
            options={'ordering': ('-pris_le',), 'verbose_name': 'Photo de chantier', 'verbose_name_plural': 'Photos de chantier'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ('nom',), 'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AlterModelOptions(
            name='typebien',
            options={'ordering': ('libelle',), 'verbose_name': 'Type de bien', 'verbose_name_plural': 'Types de biens'},
        ),
        migrations.AlterModelOptions(
            name='unite',
            options={'ordering': ('programme', 'reference_lot'), 'verbose_name': 'Unité', 'verbose_name_plural': 'Unités'},
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='contact',
            new_name='contact_commercial_nom',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='notaire',
            new_name='notaire_contact',
        ),
        migrations.RemoveField(
            model_name='modelebien',
            name='plan_image',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='image_principale',
        ),
        migrations.AddField(
            model_name='modelebien',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='contact_commercial_tel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='programme',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='notaire_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='modelebien',
            name='surface_hab_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='etapechantier',
            unique_together={('programme', 'code')},
        ),
    ]
