# Generated by Django 5.2.9 on 2025-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_avancementchantier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='programmes/'),
        ),
    ]
