# Generated by Django 5.2.9 on 2025-12-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_programme_image_principale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='contact_commercial_nom',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='contact_commercial_tel',
        ),
        migrations.AddField(
            model_name='programme',
            name='contact_commercial',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__code': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to=settings.AUTH_USER_MODEL),
        ),
    ]
