# Generated by Django 5.2.9 on 2025-12-06 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_programme_contact_commercial_nom_and_more'),
        ('sales', '0006_contrat_otp_generated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvancementChantierUnite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etape', models.CharField(max_length=100)),
                ('date_pointage', models.DateField()),
                ('pourcentage', models.PositiveIntegerField(default=0, help_text="Pourcentage d'avancement (0-100)")),
                ('commentaire', models.TextField(blank=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avancements_chantier', to='sales.reservation')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements_chantier', to='catalog.unite')),
            ],
            options={
                'verbose_name': 'Avancement chantier unité',
                'verbose_name_plural': 'Avancements chantier unités',
                'ordering': ('unite', '-date_pointage'),
            },
        ),
        migrations.CreateModel(
            name='PhotoChantierUnite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='chantiers/unites/')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pris_le', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Description de la photo')),
                ('avancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.avancementchantierunite')),
            ],
            options={
                'verbose_name': 'Photo chantier unité',
                'verbose_name_plural': 'Photos chantier unités',
                'ordering': ('-pris_le',),
            },
        ),
    ]
