# Generated by Django 5.2.9 on 2025-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_avancementchantierunite_photochantierunite'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='statut_chantier',
            field=models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('livre', 'Livré')], default='non_commence', help_text="Suivi de la progression de construction de l'unité", max_length=20),
        ),
    ]
