# Generated by Django 5.2.9 on 2025-12-06 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_unite_statut_chantier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(help_text='Contenu du message')),
                ('lu', models.BooleanField(default=False, help_text='Message lu par le destinataire')),
                ('auteur', models.ForeignKey(help_text='Auteur du message (client ou commercial)', on_delete=django.db.models.deletion.CASCADE, related_name='messages_chantier', to=settings.AUTH_USER_MODEL)),
                ('avancement', models.ForeignKey(help_text='Avancement concerné par le message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='catalog.avancementchantierunite')),
            ],
            options={
                'verbose_name': 'Message chantier',
                'verbose_name_plural': 'Messages chantier',
                'ordering': ('created_at',),
            },
        ),
    ]
