# Generated by Django 5.2.9 on 2025-12-06 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_messagechantier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechantier',
            name='repondu_par',
            field=models.ForeignKey(blank=True, help_text='Commercial qui a répondu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_messages_chantier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagechantier',
            name='reponse',
            field=models.TextField(blank=True, help_text='Réponse du commercial (optionnel)', null=True),
        ),
    ]
