# Generated by Django 5.2.9 on 2025-12-06 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_messagechantier_repondu_par_messagechantier_reponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechantier',
            name='supprime_par',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs qui ont supprimé ce message (soft delete)', related_name='messages_chantier_supprimes', to=settings.AUTH_USER_MODEL),
        ),
    ]
