# Generated by Django 5.2.9 on 2025-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_increase_gps_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='type_operation',
            field=models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', help_text='Vente ou Location', max_length=20),
        ),
    ]
