# Generated by Django 5.2.9 on 2025-12-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_programme_type_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelebien',
            name='prix_base_ttc',
        ),
    ]
