# Generated by Django 5.2.8 on 2025-11-10 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanquePartenaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('code_banque', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('kyc_statut', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_etude', 'En étude'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('clos', 'Clos')], default='soumis', max_length=20)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financements', to='sales.banquepartenaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_echeance', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_etude', 'En étude'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('clos', 'Clos')], default='soumis', max_length=20)),
                ('financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='sales.financement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('expiree', 'Expirée')], default='en_cours', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='sales.client')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.unite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('moyen', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='enregistre', max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='sales.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='financement',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financement', to='sales.reservation'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('signe', 'Signé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('signe_le', models.DateTimeField(blank=True, null=True)),
                ('pdf_hash', models.CharField(blank=True, max_length=128)),
                ('otp_logs', models.JSONField(blank=True, default=dict)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='sales.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
