# Generated by Django 5.2.9 on 2025-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='echeance',
            options={'ordering': ('date_echeance',), 'verbose_name': 'Échéance', 'verbose_name_plural': 'Échéances'},
        ),
        migrations.AlterModelOptions(
            name='financement',
            options={'verbose_name': 'Financement', 'verbose_name_plural': 'Financements'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numero',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('carte', 'Carte bancaire')], max_length=50),
        ),
    ]
