# Generated by Django 5.2.9 on 2025-12-04 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_contrat_options_alter_echeance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('cni', 'CNI'), ('photo', 'Photo/Selfie'), ('residence', 'Preuve de résidence')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/reservations/%Y/%m/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('raison_rejet', models.TextField(blank=True)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.reservation')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_documents_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de réservation',
                'verbose_name_plural': 'Documents de réservation',
                'ordering': ['-created_at'],
                'unique_together': {('reservation', 'document_type')},
            },
        ),
    ]
