# Generated by Django 5.2.9 on 2025-12-05 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_reservationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('brochure', 'Brochure du programme'), ('cni', 'CNI'), ('bulletin_salaire', 'Bulletin de salaire'), ('rib_ou_iban', 'RIB ou IBAN'), ('attestation_employeur', "Attestation d'employeur")], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/financements/%Y/%m/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('raison_rejet', models.TextField(blank=True)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.financement')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_documents_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de financement',
                'verbose_name_plural': 'Documents de financement',
                'ordering': ['-created_at'],
                'unique_together': {('financement', 'document_type')},
            },
        ),
    ]
