# Generated by Django 5.2.9 on 2025-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_financementdocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financementdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financementdocument',
            name='numero_ordre',
            field=models.IntegerField(default=1, help_text="Numéro d'ordre pour les documents multiples (ex: 1er, 2e, 3e bulletin)"),
        ),
        migrations.AlterUniqueTogether(
            name='financementdocument',
            unique_together={('financement', 'document_type', 'numero_ordre')},
        ),
    ]
