# Generated by Django 5.2.9 on 2025-12-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_financementdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de génération du dernier OTP', null=True),
        ),
    ]
