# Generated by Django 5.2.9 on 2025-12-06 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_contrat_otp_generated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='annulee_le',
            field=models.DateTimeField(blank=True, help_text="Date/heure d'annulation", null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='annulee_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a annulé la réservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='motif_annulation',
            field=models.TextField(blank=True, help_text="Motif de l'annulation par le commercial", null=True),
        ),
    ]
