# Generated by Django 5.2.9 on 2025-12-08 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_reservation_cancellation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='duree_mois',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Durée du bail en mois au moment de la signature', null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('acompte', 'Acompte'), ('solde', 'Solde'), ('echéance_loyer', 'Échéance de loyer'), ('caution', 'Caution')], default='acompte', help_text='Acompte, Solde, Échéance loyer ou Caution', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='duree_bail_mois',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Durée du bail en mois (12, 24, 36...)', null=True),
        ),
        migrations.CreateModel(
            name='EcheanceLoyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_mois', models.PositiveIntegerField(help_text='Numéro du mois (1, 2, 3...)')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du loyer pour ce mois', max_digits=12)),
                ('date_echeance', models.DateField(help_text="Date d'échéance du paiement")),
                ('statut_paiement', models.CharField(choices=[('enregistre', 'Enregistré'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='enregistre', help_text='Statut du paiement pour cette échéance', max_length=20)),
                ('paiement', models.OneToOneField(blank=True, help_text='Paiement associé (null si non payé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeance_loyer', to='sales.paiement')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances_loyer', to='sales.reservation')),
            ],
            options={
                'verbose_name': 'Échéance loyer',
                'verbose_name_plural': 'Échéances loyer',
                'ordering': ['reservation', 'numero_mois'],
                'unique_together': {('reservation', 'numero_mois')},
            },
        ),
    ]
