# Generated by Django 5.2.9 on 2025-12-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_contrat_duree_mois_paiement_type_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, help_text='Remarques supplémentaires sur le paiement', null=True),
        ),
    ]
