# Generated by Django 5.2.9 on 2025-12-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_paiement_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='recu_emis_le',
            field=models.DateTimeField(blank=True, help_text='Date et heure de génération du reçu', null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recu_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées du reçu (numéro, info client, etc.)'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recu_pdf',
            field=models.FileField(blank=True, help_text='Reçu généré automatiquement au format PDF', null=True, upload_to='paiements/recus/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
