# Generated by Django 5.2.9 on 2025-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_paiement_recu_emis_le_paiement_recu_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='client_adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contrat',
            name='client_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contrat',
            name='commercial_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contrat',
            name='commercial_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='conditions_generales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='conditions_particulieres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='generated_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='lieu_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='programme_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='unite_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrat',
            name='unite_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
