# Generated by Django 5.2.9 on 2025-12-11

from django.db import migrations


def _run_sql(sql):
    return migrations.RunSQL(sql, reverse_sql=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_contrat_client_adresse_contrat_client_email_and_more'),
    ]

    operations = [
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS client_nom varchar(255) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS client_email varchar(254) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS client_telephone varchar(50) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS client_adresse varchar(255) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS programme_nom varchar(255) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS unite_reference varchar(100) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS unite_description varchar(255) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS montant_total numeric(12, 2)
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS date_signature date
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS date_fin date
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS lieu_signature varchar(255) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS conditions_generales text NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS conditions_particulieres text NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS commercial_nom varchar(255) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS commercial_email varchar(254) NOT NULL DEFAULT ''
        """),
        _run_sql("""
            ALTER TABLE sales_contrat
            ADD COLUMN IF NOT EXISTS generated_pdf boolean NOT NULL DEFAULT FALSE
        """),
    ]
