# Generated by Django 5.2.9 on 2025-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_add_missing_contrat_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='financement',
            name='justificatif_financement',
            field=models.FileField(blank=True, help_text='Justificatif de financement bancaire (PDF/JPG/PNG max 5MB)', null=True, upload_to='documents/financements/justificatifs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='financement',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='statut',
            field=models.CharField(choices=[('justificatif_soumis', 'Justificatif soumis'), ('accepte', 'Financement accepté'), ('refuse', 'Financement rejeté')], default='justificatif_soumis', max_length=20),
        ),
        migrations.AlterField(
            model_name='financement',
            name='statut',
            field=models.CharField(choices=[('justificatif_soumis', 'Justificatif soumis'), ('accepte', 'Financement accepté'), ('refuse', 'Financement rejeté')], default='justificatif_soumis', max_length=20),
        ),
    ]
