# Generated by Django 5.2.9 on 2025-12-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_financement_justificatif_financement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financement',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
